name: Update badges

on:
  schedule:
    # Runs at 0am UTC
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Certifications
        uses: qvipin/qvipin@main
        with:       
          CREDLY_USER: vipin-b.891c3b63
